export const sampleCourses = [
  {
    id: "grammar-101",
    title: "Grammar Basics",
    description: "Master the fundamentals of English grammar",
    color: "bg-gradient-to-br from-blue-600 to-blue-800",
    icon: "📚",
    progress: 45,
    locked: false,
  },
  {
    id: "vocab-builder",
    title: "Vocabulary Builder",
    description: "Expand your English vocabulary",
    color: "bg-gradient-to-br from-green-600 to-green-800",
    icon: "📖",
    progress: 30,
    locked: false,
  },
  {
    id: "writing-skills",
    title: "Writing Skills",
    description: "Improve your English writing",
    color: "bg-gradient-to-br from-purple-600 to-purple-800",
    icon: "✍️",
    progress: 0,
    locked: false,
  },
  {
    id: "speaking-practice",
    title: "Speaking Practice",
    description: "Build confidence in speaking",
    color: "bg-gradient-to-br from-orange-600 to-orange-800",
    icon: "🎤",
    progress: 0,
    locked: true,
  },
  {
    id: "listening-comprehension",
    title: "Listening Comprehension",
    description: "Improve your listening skills",
    color: "bg-gradient-to-br from-pink-600 to-pink-800",
    icon: "🎧",
    progress: 0,
    locked: true,
  },
  {
    id: "idioms-expressions",
    title: "Idioms & Expressions",
    description: "Learn common English idioms",
    color: "bg-gradient-to-br from-indigo-600 to-indigo-800",
    icon: "💡",
    progress: 0,
    locked: true,
  },
]
